spring.application.name=orthanc-scan-producer
server.port=3000

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

app.scans.exchange=orthanc.scans
app.scans.queue=orthanc.scans
app.scans.routing-key=scan.created

app.cors.allowed-origins=http://localhost:4200
